chore: update hutte.yml scripts and version

diff --git a/hutte.yml b/hutte.yml
--- a/hutte.yml
+++ b/hutte.yml
@@ -1,10 +1,10 @@
-version: 1.0
+version: "1.0"
 
 # Shell script to run when pushing the source code to the scratch orgs.
 # It's a great place to automate tasks like permission set assignments or data loading.
 push_script: |
-  sf --version
-  sf project deploy start --wait 60 --ignore-conflicts
+  set -euo pipefail # fail fast
+  sf project deploy start
 
 custom_scripts:
   # This scripts will be displayed on the scratch org's page
@@ -12,11 +12,13 @@ custom_scripts:
     'Import Data':
       description: "Import data using SFDMU"
       run: |
+        set -euo pipefail # fail fast
         echo y | sf plugins install sfdmu
         sf sfdmu run -p data -s csvfile -u "${SALESFORCE_USERNAME}" --filelog 0 -n
     'Export Data':
       description: "Export data using SFDMU"
       run: |
+        set -euo pipefail # fail fast
         echo y | sf plugins install sfdmu
         sf sfdmu run -p data -s "${SALESFORCE_USERNAME}" -u csvfile --filelog 0 -n
         git add data
